export const GET_HIGH_STOCK_REQUEST = 'GET_HIGH_STOCK_REQUEST_REQUEST';
export const GET_HIGH_STOCK_REQUEST_SUCCESS = 'GET_HIGH_STOCK_REQUEST_SUCCESS';
export const GET_HIGH_STOCK_REQUEST_ERROR = 'GET_HIGH_STOCK_REQUEST_ERROR';

export const TOGGLE_CHART_TYPE = 'TOGGLE_CHART_TYPE';
export const TOGGLE_CHART = 'TOGGLE_CHART';
