export const HEROES_TYPE_ATTACK_FETCH = 'HEROES_TYPE_ATTACK_FETCH';
export const HEROES_TYPE_ATTACK_FETCH_SUCCESS = 'HEROES_TYPE_ATTACK_FETCH_SUCCESS';

export const HEROES_PRIMARY_ATTR_FETCH = 'HEROES_PRIMARY_ATTR_FETCH';
export const HEROES_PRIMARY_ATTR_FETCH_SUCCESS = 'HEROES_PRIMARY_ATTR_FETCH_SUCCESS';
