export const HIGH_STOCK_DATA_FETCH = 'HIGH_STOCK_DATA_FETCH';
export const HIGH_STOCK_DATA_FETCH_SUCCESS = 'HIGH_STOCK_DATA_FETCH_SUCCESS';
export const HIGH_STOCK_DATA_FETCH_ERROR = 'HIGH_STOCK_DATA_FETCH_ERROR';

export const HIGH_STOCK_CONFIG_SET = 'HIGH_STOCK_CONFIG_SET';
export const HIGH_STOCK_CONFIG_FETCH = 'HIGH_STOCK_CONFIG_FETCH';
export const HIGH_STOCK_CONFIG_FETCH_SUCCESS = 'HIGH_STOCK_CONFIG_FETCH_SUCCESS';
export const HIGH_STOCK_CONFIG_FETCH_ERROR = 'HIGH_STOCK_CONFIG_FETCH_ERROR';
