export const GET_HIGH_STOCK_REQUEST = 'GET_HIGH_STOCK_REQUEST';
export const GET_HIGH_STOCK_REQUEST_SUCCESS = 'GET_HIGH_STOCK_REQUEST_SUCCESS';
export const GET_HIGH_STOCK_REQUEST_ERROR = 'GET_HIGH_STOCK_REQUEST_ERROR';

export const SET_HIGH_STOCK_CONFIG_REQUEST = 'SET_HIGH_STOCK_CONFIG_REQUEST';
export const GET_HIGH_STOCK_CONFIG_REQUEST = 'GET_HIGH_STOCK_CONFIG_REQUEST';
export const GET_HIGH_STOCK_CONFIG_REQUEST_SUCCESS = 'GET_HIGH_STOCK_CONFIG_REQUEST_SUCCESS';
export const GET_HIGH_STOCK_CONFIG_REQUEST_ERROR = 'GET_HIGH_STOCK_CONFIG_REQUEST_ERROR';
