export const MATCHES_FB_TO_TIME_FETCH = 'MATCHES_FB_TO_TIME_FETCH';
export const MATCHES_FB_TO_TIME_FETCH_SUCCESS = 'MATCHES_FB_TO_TIME_FETCH_SUCCESS';

export const MATCHES_DATA_FETCH = 'MATCHES_DATA_FETCH';
export const MATCHES_DATA_FETCH_SUCCESS = 'MATCHES_DATA_FETCH_SUCCESS';

export const MATCHES_EXPANDED_DATA_FETCH = 'MATCHES_EXPANDED_DATA_FETCH';
export const MATCHES_EXPANDED_DATA_FETCH_SUCCESS = 'MATCHES_EXPANDED_DATA_FETCH_SUCCESS';
