export const MATCHES_FB_TO_TIME_FETCH = 'MATCHES_FB_TO_TIME_FETCH';
export const MATCHES_FB_TO_TIME_FETCH_SUCCESS = 'MATCHES_FB_TO_TIME_FETCH_SUCCESS';

export const MATCHES_DATA_FETCH = 'MATCHES_DATA_FETCH';
export const MATCHES_DATA_FETCH_SUCCESS = 'MATCHES_DATA_FETCH_SUCCESS';

export const MATCHES_EXPANDED_DATA_FETCH = 'MATCHES_EXPANDED_DATA_FETCH';
export const MATCHES_EXPANDED_DATA_FETCH_SUCCESS = 'MATCHES_EXPANDED_DATA_FETCH_SUCCESS';

export const START_SET_NESTED_OBJECT = 'START_SET_NESTED_OBJECT';
// export const FINISH_SET_NESTED_OBJECT = 'FINISH_SET_NESTED_OBJECT';

export const START_REMOVE_NESTED_OBJECT = 'START_REMOVE_NESTED_OBJECT';
// export const FINISH_REMOVE_NESTED_OBJECT = 'FINISH_REMOVE_NESTED_OBJECT';
